import enviroments from "~/config";
import {
    ProductsIndexMethodsPaginator,
    ProductsIndexTable,
} from "@/products/lib/ProductsColumns";
import { useQuery, type UseQuery } from "@vigilio/preact-fetching";

export type ProductsPaginatorQuery = UseQuery<
    ProductsPaginatorAPI,
    ProductsPaginatorErrorAPI
>;
export function productsPaginatorApi(
    table: ProductsIndexTable
): ProductsPaginatorQuery {
    const query = useQuery<ProductsPaginatorAPI, ProductsPaginatorErrorAPI>(
        "/products",
        async function (url) {
            const data = new URLSearchParams();
            data.append("offset", String(table.pagination.value.offset));
            data.append("search", table.search.debounceTerm);
            data.append("limit", String(table.pagination.value.limit));

            if (!Object.keys(table.sort.value).length) {
                data.append("id", "DESC");
            }
            for (const [key, value] of Object.entries(table.sort.value)) {
                data.append(key, value as string);
            }
            const response = await fetch(
                `${enviroments.VITE_URL}/api/paginator${url}?${data}`
            );
            const result = await response.json();
            if (!result.success) throw result;
            return result;
        },
        {
            onSuccess(data) {
                table.updateData({
                    count: data.count,
                    result: data.results,
                    methods: {
                        refetch: query.refetch,
                    } as ProductsIndexMethodsPaginator,
                });
            },
            clean: false,
        }
    );
    return query;
}

// Generated by https://quicktype.io

export interface ProductsPaginatorAPI {
    success: boolean;
    count: number;
    next: string;
    previous: null;
    results: Product[];
}

export interface Product {
    id: number;
    name: string;
    description: string;
    price: string;
    images: Image[];
    stock: null;
    ilimit: boolean;
    slug: string;
    category_id: number;
    createdAt: string;
    updatedAt: string;
}

export interface Image {
    dimension: number;
    file: string;
}
export interface ProductsPaginatorErrorAPI {
    success: boolean;
    message: string;
    params: string;
}
